#%RAML 1.0 DataType
type: object
properties: 
  name: string
  gender: string
  maritalStatus: string
  phone: string
  email: string
  dateOfBirth: date-only
example: !include ../examples/AccountExample.raml
  
  
